### ISSUE TITLE
Папка Шаблоны в домашнем каталоге

### ISSUE THREAD

**Issue by maplee0** [sde-gui/stuurman#32]
При запуске stuurman зачем-то создает папку Шаблоны в домашнем каталоге, хотя нигде настроек нет таких. Я не знаю, какой компонент это делает (libsmfm-* или сам stuurman), написал сюда.

**Comment by wandrien** [comment]
Это поведение в соответствии с https://www.freedesktop.org/wiki/Software/xdg-user-dirs/

Местоположение каталога задаётся в файле `~/.config/user-dirs.dirs`.

Например, на моём компе:

```sh
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run
# Format is XDG_xxx_DIR="$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
# 
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/"
XDG_TEMPLATES_DIR="$HOME/Templates"
XDG_PUBLICSHARE_DIR="$HOME/"
XDG_DOCUMENTS_DIR="$HOME/"
XDG_MUSIC_DIR="$HOME/"
XDG_PICTURES_DIR="$HOME/"
XDG_VIDEOS_DIR="$HOME/"
```

Если вам вообще не нужна поддержка пользовательских шаблонов, то попробуйте в XDG_TEMPLATES_DIR вписать `/var/empty/` - системно предусмотренный всегда пустой каталог.

**Comment by maplee0** [comment]
Спасибо!
